In [2]:
import cv2
import numpy as np

src = cv2.imread("../images/rose1.jpg")   # 입력 영상 불러오기
data = src.reshape((-1, 3)).astype(np.float32) #픽셀수만큼의 행*3채널로 차원 변환 & np.float32 자료형 변환

# K-means 알고리즘
criteria = (cv2.TERM_CRITERIA_EPS|cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0) #10번 반복 중 정확도 1.0이 되면 중단

for K in range(2, 20):
    print("K:", K)
    ret, label, center = cv2.kmeans(data, K, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS)

    # 군집화 결과를 이용하여 출력 영상 생성
    center = np.uint8(center)
    if K < 4:
        print(center)
        print(label) # ex)1, 2, 2, 0 ... : 첫번째 픽셀은 1번째 군집, 두번째 픽셀은 2번째 군집...
    dst = center[label.flatten()]  # 각 픽셀을 K개 군집 중심 색상으로 치환
    dst = dst.reshape((src.shape))

    cv2.imshow("src", src)
    cv2.imshow("dst", dst)
    cv2.waitKey()

cv2.destroyAllWindows()


K: 2
[[ 44 118 200]
 [ 49  42  29]]
[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
K: 3
[[ 56  23 186]
 [ 34 175 200]
 [ 50  44  21]]
[[2]
 [2]
 [2]
 ...
 [2]
 [2]
 [2]]
K: 4
K: 5
K: 6
K: 7
K: 8
K: 9
K: 10
K: 11
K: 12


KeyboardInterrupt: 